# Comandos padrões para usar com o Makefile

.PHONY: up-dev up-prod

up-dev:
	@chmod +x scripts/up-dev.sh
	@scripts/up-dev.sh

up-prod:
	@chmod +x scripts/up-prod.sh
	@scripts/up-prod.sh

# Outros comandos de make conforme necessário
